comments = [
  "Woah!",
  "Where did you take this?",
  "That's so cool!!",
  "Liked the right one this time lol 😂",
  "😍😍😍",
  "Wish I could come",
  "Enjoy your weekend❤️",
  "All the greens",
  "My favorite word",
  "How cute!",
  "It ain’t over, ya know. 😏",
  "it looks like light weight lol",
  "This is going too far...",
  "Actually, I prefer to hum my own soft tune. Helps the kale relax... heh heh",
  "So good 😍😍",
  "So fresh!",
  "Sometimes it just helps to cut corners!",
  "Where???? Was it awesome? I want to try",
  "Were you there today ? I was there. 😂😂😂😂😂🤘🏽🤘🏽🤘🏽🤘🏽",
  "Noicee",
  "HAHAHA",
  "👏👏👏👏👏👏👏👏",
  "Krazy fun......Right?",
  "Our Sir Belvebear is back in business, welcome back, good friend. It's been a while",
  "I got you fam",
  "Welcome back!",
  "It's beautiful!!",
  "Damn, working hard guys!",
  "Love from Greece guys❤",
  "I wish i could go :( Lmk the next time you're going and maybe I can join you!",
  "love this!",
  "That's me but in reverse",
  "my main inspiration",
  "So warm....",
  "I love these posts of yours!",
  "Will check it out!",
  "Arg and I'm not there😑",
  "I might see you guys on Sunday!",
  "Blue Collar Work Ethic. White Collar Mindset. Can't Stop, Won't Stop, Don't Stop",
  "💕love you!!",
  "Impressive shot.",
  "Slayyyy",
  "Shout out to this little guy.",
  "❤️👯love u!!",
  "where were you?",
  "Love this! That last picture makes me miss him so much.",
  "There's too many worlds colliding",
  "So much fun!",
  "Very very excellent",
  "Omg who are you....😥",
  "LOLOLOL",
  "Superb!",
  "☃️Not sure how I survived in New England all these years",
  "This is really good",
  "I thought there would be more trees here",
  "amazing!",
  "OMG WE ARE NEIGHBORS!! Let me know if you're looking for places to hang in the area",
  "Sick photo man",
  "what a troll 😂😂😂👌",
  "Gorgeous!!",
  "Oh. God. That's. Hot.",
  "You are a beaut!!!😍",
  "worth the hype?",
  "So beautiful",
  "Cool!",
  "These look so nice",
  "Bused three hours for this 🔥",
  "Everything hurts 🙂",
  "Omg yes!! 👏👏",
  "That split tho 😏",
  "Nice, follow us pls <3",
  "Life goes on, with or without you.",
  "digging through the archives for these, are we",
  "I feel ya!",
  "we need to get on her level!",
  "LOVE! 🗽",
  "Omggg this caption 😂😂 You, my friend, are on top of your PXLG game, hahaha",
  "These are such good photos!",
  "Miss ya lil fella",
  "How are you so amazing",
  "I like this photo!!",
  "Peace of mind!!",
  "so excited to hear about your new adventures!",
  "...it’s all uphill from here 😊😊",
  "Is the food there good? 😂",
  "You were literally on my street. Always so close but so far",
  "big foig",
  "woohoo can’t wait to hear all about it friday :)",
  "Awesome!!! ❤",
  "Hy",
  "Picture perfect!!",
  "Ooooo. This is dopppppe",
  "What in the world",
  "So worth it",
  "What is this! So pretty 😍",
  "Love this! Awesome",
  "Conquering one adventure at a time.",
  "Hi I just started an art instagram it would mean so much if someone took a look. Thanks so much😁",
  "I forgot Its summer in Australia.",
  "Dope!",
  "Whoaaaaa",
  "Love your feed",
  "Jokes 🃏🤹",
  "Loving your photography while venturing.",
  "Beast of a camera",
  "Wow I'm jealous lol. When were you there? I'm thinking of planning some time off..",
  "hehehe",
  "You took that yourself, huh",
  "This is fierce!",
  "Magic!",
  "It's beautiful!!",
  "Wow! Love this!",
  "So cool !! I'm a little envious.",
  "Beautiful shot!!! And awesome photos on your page 👌🏽",
  "does this look familiar? Haha",
  "Illuminati 👀",
  "⭐",
  "So nice!",
  "Dude you better be using sunscreen bruh",
  "What are you doing on Friday 👀 lol",
  "You look amazing ✨ so inspiring",
  "DUDEEEEEEEEE, this is crazy! Great shot, I'm lookin forward to seeing more",
  "amazed!",
  "You are an amazing person!",
  "You're killin it",
  "Love you man !! Keep Grinding!!",
  "This is way better then that new Jake Paul bs",
  "Push it to the limit! You got this! 💪👏🏻😂",
  "Yessssssss killlling it!",
  "Hey bro, are u a powerlifter?",
  "LOL this will be me next time",
  "Oh you got that good stuff",
  "Welcome to the GOOD LIFE 😂",
  "I'll see you in the afterlife.",
  "Holy crap did you guys see the ALIENS flying over LA?!",
  "The iconic “why are you doing this to me??” face. 😂",
  "This is what you do at work?",
  "This view looks beautiful!! 😍😍",
  "I've been here twice",
  "Why leaving so early?!?! I was gonna go there next week with Michael, lmk if you're still around",
  "BADASS! 💪🏽💢",
  "You are my inspiration",
  "Power!!🔥🔥🔥",
  "When are you running in your Batman suit",
  "Holyyy! Angelina Jolie!!",
  "I found my source of power and strength. 🤤😍 Thanks for sharing this photo. It is truly inspirational",
  "Just saw your Hyundai ad on Snapchat LMAO",
  "I didn't even know you posted this! 😂",
  "Keep it up fam",
  "The dedication is real",
  "Freaking beast, keep up the hard work brotha! This is super motivational",
  "This pic is so cool 👌",
  "y'all look so alike now",
  "I'm going on friday!! How long are you staying there for?",
  "My guy why aren’t you verified yet?",
  "So epic!",
  "Looking like 💰💰💰",
  "Back at it again with the short shorts",
  "Thisss is amazing!!!! Keep it up!",
]

###########
# COMMENTS
###########

Comment.destroy_all

220.times do
  Comment.create!(user_id: USER_IDS.sample,
    photo_id: PHOTO_IDS.sample,
    body: comments.sample)
end
