ALL_COMMENTS = [
  "Woah!",
  "Where did you take this?",
  "That's so cool!!",
  "Liked the right one this time lol 😂",
  "😍😍😍",
  "Wish I could come",
  "Enjoy your weekend❤️",
  "All the greens",
  "My favorite word",
  "How cute!",
  "It ain’t over, ya know. 😏",
  "it looks like light weight lol",
  "This is going too far...",
  "Actually, I prefer to hum my own soft tune. Helps the kale relax...",
  "So good 😍😍",
  "So fresh!",
  "Sometimes it just helps to cut corners!",
  "Where???? Was it awesome? I want to try",
  "Were you there today ? I was there. 😂😂😂😂😂🤘🏽🤘🏽🤘🏽🤘🏽",
  "Noicee",
  "HAHAHA",
  "👏👏👏👏👏👏👏👏",
  "Krazy fun......Right?",
  "Our sir belvebear is back in business",
  "I got you fam",
  "Welcome back!",
  "It's beautiful!!",
  "Damn, working hard guys!",
  "Love from Greece guys❤",
  "i wish i could go :(",
  "love this!",
  "That's me but in reverse",
  "my main inspiration",
  "So warm....",
  "I love these posts of yours!",
  "Will check it out!",
  "Arg and I'm not there😑",
  "I might see you guys on Sunday!",
  "Blue Collar Work Ethic. White Collar Mindset.",
  "💕love you!!",
  "Impressive shot.",
  "Slayyyy",
  "Shout out to this little guy.",
  "❤️👯love u!!",
  "where were you?",
  "Love this! That last picture makes me miss him so much.",
  "There's too many worlds colliding",
  "So much fun!",
  "Very very excellent",
  "Omg who are you....😥",
  "LOLOLOL",
  "Superb!",
  "☃️Not sure how I survived in New England all these years",
  "This is really good",
  "I thought there would be more trees here",
  "amazing!",
  "OMG WE ARE NEIGHBORS!!!🔥",
  "Sick photo man",
  "what a troll 😂😂😂👌",
  "Gorgeous!!",
  "Oh. God. That's. Hot.",
  "You are a beaut!!!😍",
  "worth the hype?",
  "So beautiful",
  "Cool!",
  "These look so nice",
  "Bused three hours for this 🔥",
  "Everything hurts 🙂",
  "Omg yes!! 👏👏",
  "That split tho 😏",
  "Nice, follow us pls <3",
  "digging through the archives for these, are we",
  "I feel ya!",
  "we need to get on her level!",
  "LOVE! 🗽",
  "These are such good photos!",
  "Miss ya lil fella",
  "How are you so amazing",
  "I like this photo!!",
  "Peace of mind!!",
  "so excited to hear about your new adventures!",
  "...it’s all uphill from here 😊😊",
  "Is the food there good? 😂",
  "You were literally on my street. Always so close but so far",
  "big foig",
  "woohoo can’t wait to hear all about it friday :)",
  "Awesome!!! ❤",
  "Hy",
  "Picture perfect!!",
  "Ooooo. This is dopppppe",
  "What in the world",
  "So worth it",
  "What is this! So pretty 😍",
  "Love this! Awesome",
  "Conquering one adventure at a time.",
  "Hi I just started an art instagram it would mean so much if someone took a look. Thanks so much😁",
  "I forgot Its summer in Australia.",
  "Dope!",
  "Whoaaaaa",
  "Love your feed",
  "Jokes 🃏🤹",
  "Loving your photography while venturing.",
  "Beast of a camera",
  "Wow I'm jealous lol",
  "hehehe",
  "You took that yourself huh",
  "This is fierce!",
  "Magic!",
  "So cool !! I'm a little envious.",
  "Beautiful shot!!! And awesome photos on your page👌🏽",
  "does this look familiar? Haha",
  "Illuminati 👀",
  "⭐",
  "So nice!",
  "Dude you better be using sunscreen bruh",
  "What are you doing on Friday 👀 lol"
]
